### ISSUE TITLE
Consider an events collector for certain CF queries

### ISSUE THREAD

**Issue by jonathaningram** [bosh-prometheus/cf_exporter#20]
Would you be interested in accepting a PR for an events collector? 

The particular case I'm interested in is a metric for the total number of deployments.

If my understanding of the CF API is correct, this is essentially the query: `GET /v2/events?q=type:audit.app.build.create`. The collector would simply look at the value of `total_results` in the JSON response and that would be the total number of app deployments over all time.

With that metric, I think prometheus can do the rest, e.g. "how many deployments today", "how many deployments yesterday".

Thoughts?

**Comment by jonathaningram** [comment]
Update: thinking about this overnight, I realised that in my use case I would want the total events matching that `type` but then I'd also want to be able to query prometheus and put filters on like `organization_name!="system"` so that we aren't counting deployments from our system applications.

Given this extra information, I'm wondering if it's better for `cf_exporter` to instead just send all events off to prometheus. The trick will be to make sure that `cf_exporter` can track what events it is up to - on a first pass it would send all known events, however subsequent passes it should only send new events.

**Comment by frodenas** [comment]
There was already an `App Events` collector, but it was removed (commit https://github.com/bosh-prometheus/cf_exporter/commit/71922c528a1c5cfc12c8c113c48b655ce5c39242). There're basically 2 problems:
1) you cannot send events to prometheus, you need to report a metric, and usually, this would be some kind of aggregation (like count) of events of a particular type
2) the events api is extremely slow and puts lots of stress on the CC (see https://github.com/bosh-prometheus/cf_exporter/issues/16). For small deployments, collecting events should be fine, but when dealing with large deployments, it's completely unusable unless you add some state to the collector (like fetching events using a page token), and this is out of scope of this exporter.

**Comment by jonathaningram** [comment]
@frodenas I really appreciate your response, thanks.
