### ISSUE TITLE
cf_application_info shows "STARTED" when app is actually crashed

### ISSUE THREAD

**Issue by timlharrison** [bosh-prometheus/cf_exporter#25]
I've noticed that both the cf_application_info and cf_application_instances metrics will show a crashed app as "STARTED" rather than "CRASHED" even if all AIs are in a crashed state.  The API shows the instances as "state": "CRASHED" if you cf curl the /v2/apps/<app_guid>/stats API.

**Comment by frodenas** [comment]
To report those metrics, the exporter is using the [Get Space summary](https://apidocs.cloudfoundry.org/4.3.0/spaces/get_space_summary.html) API. Can you please check if that API call is also returning the same info for the app?

**Comment by timlharrison** [comment]
You're right - the Space Summary API shows the app as started even though all instances are crashed.  Not sure if that is a CF API deficiency or by design since the desired state of the app is "STARTED".  Not sure where to go from here - currently there's no way that I know of to detect crashed AIs within a specific org/space/app.  Maybe a new metric cf_application_instances_crashed (similar to cf_application_instances_running) which dumps all the same tags for crashed AIs?

**Comment by frodenas** [comment]
Check the [app alerts](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/jobs/cloudfoundry_alerts/templates/cf_apps.alerts.yml), the `CFAppUnhealthy` may give what you're looking for.

**Comment by timlharrison** [comment]
Thats perfect.  Thank you.
