### ISSUE TITLE
Applications_collector does not limit concurrency

### ISSUE THREAD

**Issue by Freakin** [bosh-prometheus/cf_exporter#26]
With a large CF Foundation (400 orgs, 2650 spaces, 15,500 apps) the applications collector is making hundreds to thousands of concurrent SpaceSummary API calls.  

I am hitting open file limits on cf_exporter due to the large number of concurrent goroutines all making DNS and API calls.

Could configurable concurrency limits be set with something like SizedWaitGroup?
https://github.com/remeh/sizedwaitgroup

**Comment by amhuber** [comment]
We are seeing this also.

**Comment by frodenas** [comment]
Fixed at https://github.com/bosh-prometheus/cf_exporter/commit/88e965567747432ba6056c4b07d3d461d0c6c543. 

Right now the number of concurrent goroutines is fixed using a safe number (10 concurrent organizations * 10 concurrent spaces).
