### ISSUE TITLE
feature: label isolation_segment in metric application_info 

### ISSUE THREAD

**Issue by androyamamoto** [bosh-prometheus/cf_exporter#27]
Hi,
is it possible to add the label isolation_segment into the metric application_info?

We are writing an app to scratch prometheus for specific KPIs for our platform-dashboard.
For us it would be really nice if we could get the label isolation_segment to summarize which app runs in which isolation segment.

Best,
André

**Comment by frodenas** [comment]
@androyamamoto The [go-cfclient](https://github.com/cloudfoundry-community/go-cfclient) library used by this exporter [does not implement](https://github.com/cloudfoundry-community/go-cfclient/blob/master/isolationsegments.go#L145) yet the logic to return `Isolation Segment` information for `Organizations` and `Spaces`  Can you please open an issue and/or a PR at the [go-cfclient](https://github.com/cloudfoundry-community/go-cfclient) repo?
