### ISSUE TITLE
feature: last_operation in service and service binding metrics

### ISSUE THREAD

**Issue by gberche-orange** [bosh-prometheus/cf_exporter#29]
As a service operator, in order to get alerted on failed asynchronous service instances, I would like to have [service metrics](https://github.com/bosh-prometheus/cf_exporter#metrics) include the status of services instances, i.e. the last_operation (type=create|update|delete and state=in_progress|succeeded|failed) returned by the [list_all_service_instances api](http://apidocs.cloudfoundry.org/6.5.0/service_instances/list_all_service_instances.html)

As a service operator, in order to get alerted on failed asynchronous service bindings, I would like to have [service binding metrics](https://github.com/bosh-prometheus/cf_exporter#metrics) include the status of services instances, i.e. the last_operation (type=create|update|delete and state=in_progress|succeeded|failed) returned by the [list_all_service_bindings api](http://apidocs.cloudfoundry.org/6.5.0/service_bindings/list_all_service_bindings.html)

**Comment by frodenas** [comment]
@gberche-orange The [go-cfclient](https://github.com/cloudfoundry-community/go-cfclient) library used by this exporter does not report the `last_operation` hash as part of the [ListServiceBindings](https://github.com/cloudfoundry-community/go-cfclient/blob/master/service_bindings.go#L25) response. Can you please open an issue and/or a PR at the [go-cfclient](https://github.com/cloudfoundry-community/go-cfclient) repo?

**Comment by gberche-orange** [comment]
thanks @frodenas for looking into this issue!

Indeed, the `last_operation` response field is only useful for tracking status of asynchronous service instance and service bindings, and won't help for monitoring failure of synchronous service instances/bindings: even through the last_operation properly provides success status of synchronous provisionning/bindings (see [associated sapi story](https://www.pivotaltracker.com/story/show/155357777)), synchronous failures don't leave a service instance/service binding object available for later inspection.

The go-cfclient currently support async service instances, through the [ServiceInstance.LastOperation](https://github.com/cloudfoundry-community/go-cfclient/blob/f136f9222381e2fea5099f62e4b751dcb660ff82/service_instances.go#L44) which seems available for use by the cf-exporter.

I submitted a related issue https://github.com/cloudfoundry-community/go-cfclient/issues/229 for the more recent async service binding support.

It might make sense to tackle monitoring of async service instance first as there is likely a broader service broker currently using this support, and then async service binding as a 2nd step ?

I'm sorry that I am unable contribute more than use-cases/specs here.

**Comment by frodenas** [comment]
I somewhat misread your request and thought you were just asking for ServiceBindings. 

ServiceInstance now returns the LastOperation type and state (https://github.com/bosh-prometheus/cf_exporter/commit/6611f15d536bbf667bacf452b80178a2f19eeda9). I'll wait for https://github.com/cloudfoundry-community/go-cfclient/issues/229 to implement ServiceBinding info.

**Comment by gberche-orange** [comment]
thanks @frodenas ! 

Looking forward to a new cf_exporter release that prometheus-boshrelease could bump to (likely without ServiceBinding last_operation)
