### ISSUE TITLE
configure alerts that are related to a ORG Level

### ISSUE THREAD

**Issue by ranjithfd** [bosh-prometheus/cf_exporter#30]
Hi Team,

  there is any way, our Prometheus. Alertmanager configuration which is done by ORG level, in our PCF foundation.

**Comment by frodenas** [comment]
Please take a look at the [Cloudfoundry Alerts](https://github.com/bosh-prometheus/prometheus-boshrelease/tree/master/jobs/cloudfoundry_alerts/templates). Metrics contain all the information to determine which applications belong to a particular organization.
