### ISSUE TITLE
used memory metrics is not available from application level

### ISSUE THREAD

**Issue by thiyagu19841** [bosh-prometheus/cf_exporter#31]
I am seeing only  allocated memory & disc quota size  for application level metrics; but I am also looking for used memory & used disc size for each application instance.   In addition to this, CF_EXPORTER_FILTER_COLLECTORS  will allows us to filter only app or space or org.  But  I am looking for specific app related metrics rather than get the metrics for all the applications instances. Kindly help.

**Comment by frodenas** [comment]
The [CloudFoundry API](https://apidocs.cloudfoundry.org/7.5.0/) only returns the allocated memory and cpu, so this exporter cannot get that information. In order to get the used memory, cpu and disk, you need to use the [firehose exporter](https://github.com/bosh-prometheus/firehose_exporter).
