### ISSUE TITLE
cf_application_info, cf_application_instances, cf_application_instances_running delayed by one day

### ISSUE THREAD

**Issue by ghost** [bosh-prometheus/cf_exporter#34]
I have deployed cf_exporter on our pivotal cloud foundry instances, and having a Prometheus scraping it every 5 minutes. However I found that after pushing a new application, the application instance show in the result of cf_application_info, cf_application_instances and cf_application_instances_running after the application has been deployed for a day. Is there anything that I am missing here or any advice on where should I check for such delay?

**Comment by timlharrison** [comment]
@yuyang-os does the app show up immediately on the exporter itself? Is the delay in the exporter picking it up from the API or the Prometheus instance picking up from the exporter?

**Comment by dsgvasee** [comment]
I am running into similar problem. old values are still showing up on following metrics:

>`

cf_application_disk_quota_mb{} | 1
-- | --
cf_application_info{} | 1
cf_application_instances{} | 1
cf_application_instances_running{} | 1
cf_application_memory_mb{}

`
