### ISSUE TITLE
Is CF_EXPORTER_CF_DEPLOYMENT_NAME still needed?

### ISSUE THREAD

**Issue by jgeorge300** [bosh-prometheus/cf_exporter#54]
In PCF PAS v2.5, the ability to set the deployment name has been removed. All deployments are now named<tile>-<guid> by tile rather than cf (or preferred name.) This causes issues with applications deployed to windows diego cells and the grafana dashboard as the bosh_deployment in the firehose and deployment here will never be equal. 

Should CF_EXPORTER_CF_DEPLOYMENT_NAME be made optional and by default just pass back the bosh_deployment value or should it just be removed?

**Comment by benjaminguttmann-avtq** [comment]
Hi @jgeorge300 sorry for the late response, not sure if really get the problem. Can you might give an example which dashboards are not working and which values will not be equal.
