### ISSUE TITLE
Concurrent prometheus request contexts sharing a `fetcher.Worker` causes serious problems

### ISSUE THREAD

**Issue by risicle** [bosh-prometheus/cf_exporter#82]
We've recently rolled out prometheus boshrelease 28.0.0 which includes cf_exporter 1.0.0 and we're having significant reliability problems with it. This _could_ be related to #81 but I think the issues are deeper.

From the looks of it (i.e. based on a fairly brief skim of the code), there is only ever one `fetcher.Worker` created for the whole daemon, created at init time from `main` via `NewFetcher`. This one `Worker` is used when serving all prometheus requests.

The problem is it would mean all prometheus request contexts share the same:

 - `Worker.group` wait group
 - `Worker.list` work queue

and when multiple concurrent requests arrive, this would allow some bad things to happen. Firstly sharing the same `sync.WaitGroup` means that no prometheus request will appear to finish until they _all_ finish (because that's the only condition that would reduce the number back down to zero). It also means that if any worker for any reason doesn't complete, it will stop the *whole daemon* from operating properly because, again, the wait group will never decrement back to zero.

Worse, if `Worker.run` is running twice at the same time, they will both pick work items off the shared `Worker.list` indiscriminately and run the `work.handler` against their own `entry`. So the results from the two requests will get totally mixed up.

This would explain a lot of the odd behaviour we've seen from `cf_exporter` since the 1.0.0 upgrade - scrapes that never complete, daemons that "stop working" and refuse to return the results of any scrape while steadily increasing memory usage.

**Comment by psycofdj** [comment]
You are right, I'm working on this with #81
A fix will released soon and it will be bumped into prometheus-boshrelease asap

**Comment by psycofdj** [comment]
@risicle you may be interested to know that the fix has been released in **bosh-prometheus/prometheus-boshrelease** [v28.1.0](bosh-prometheus/prometheus-boshrelease/releases/tag/v28.1.0)

**Comment by risicle** [comment]
Awesome, thankyou.
